name: deploy-react app
on: push
jobs:
  deploy-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repository
        uses: actions/checkout@v4
        
      - name: npm install
        run: npm install

      - name: run npm
        run: npm run build
      
      - name: run test
        run: npm run test
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      
      
